---
title: "CT Brain Temp (Location)"
---

## Normal CT Brain

**FINDINGS:**

-   **Cerebral parenchyma:** The study reveals __________. Normal parenchymal attenuation and gray-white differentiation. The rest of imaged cerebral parenchyma appears unremarkable. No acute large territorial infarction or intraparenchymal hemorrhage is identified. 
-   **Cerebellum and posterior fossa:** Normal given a limited evaluation of the brainstem due to beam-hardening artifacts. The cerebellums appears unremarkable. 
-   **Extraaxial spaces:** No extra-axial collection is observed. 
-   **Ventricles:** Normal size of the ventricular system. No intraventricular hemorrhage. 
-   **Midline shift:** None. 
-   **Brain herniation:** None. 
-   **Vascular system:** Normal. 
-   **Calvarium and scalp:** No fracture is identified. 
-   **Skull base, sella and temporomandibular joints (TMJs):** Normal.
-   **Visualized orbits, paranasal sinuses and mastoid air cells:** Normal. 
-   **Visualized upper cervical spine:** No fracture identified.


## Cerebral parenchyma

### Normal Brain Vol.

The study reveals 

-   normal brain volume. 
-   age-appropriate brain volume.


### Brain Vol. loss

The study reveals:

`[Diffuse | Generalized]` brain volume loss, (most pronounced at ___)

-  (+) `appropriate for age`
-  (+) `advanced more than age`

with normal gray-white differentiation of the brain parenchyma.

## Posterior fossa



## Vascular system

### Athero

**Vascular system:** `[Mild | Moderate | Severe]` atherosclerotic change of the

-   (bilateral) (intracranial) ICAs
-   vertebrobasilar system

## Calvarium and scalp

**Calvarium and scalp:** Soft tissue swelling/contusion at ___ regions.

**IMPRESSION:**

- Soft tissue swelling/contusion at the ___ regions. 

## Skull base/ sella / TMJ

**Skull base, sella and temporomandibular joints (TMJs):** Unremarkable. 

## Sinuses / Air cells

### The Rest is OK

The rest of the imaged paranasal sinuses, both mastoid air cells, both orbits and nasopharynx are unremarkable.

### Mucosa thickening

**Visualized orbits, paranasal sinuses and mastoid air cells:** `[Mild | Moderate | Severe]` mucosal thickening

-   (if inspissated content) with hyperdense content

-   (if chronic sinusitis) `[mild | moderate | severe]` sclerotic bone change 

`[of | involving]` ___ sinus

**IMPRESSION:**

-   Mild = Don't mention

-   Chronic left ___ sinusitis with inspissated content and/or fungal colonization. 

#### Air-fluid Lv

**Visualized orbits, paranasal sinuses and mastoid air cells:** Air-fluid level with internal bubbles at ___ sinus.

**IMPRESSION:**

- Air-fluid level with internal bubbles at ___ sinus, possibly acute right sphenoid sinusitis. 

### Mucous retention cysts

**Visualized orbits, paranasal sinuses and mastoid air cells:** (Few) mucous retention cysts within the ___ sinus

### Hypoplasia

Hypoplasia of ___ sinuses / air cells,

### Hypopneumatize

Hypopneumatization of the ___ frontal sinus. 


## Orbit


### Lens Extraction

`{side}` = `[Bilateral | lt | rt]`

-   `{side}` len(s) extraction is observed.

-   Evidence of `{side}` lens extraction.