---
title: "CT Brain Temp (Lesion)"
---

## Short Prelim

### CT Brain NC

No

-  intracranial hemorrhage, 
-  extra-axial collection, 
-  acute large territorial infarction, 
-  midline shift or brain herniation 

identified.

### CT Brain with CM

**For CTA**

Add

-  (+) No large vessel occlusion,
-  (+) No aneurysm, dissection or other neurovascular abnormality identified.

**For Post-contrast**

Add

-  (+) No abnormal enhancing lesion,

identified.

## Infarction

### Territorial Infarction

There is/are (large) `[well | ill]`-defined hypodense lesion(s) involving

-   `[cortical | subcortical]` areas of `{lobe}`

-   (+) with associated brain swelling


likely `{time}` (large) territorial infarction of `{artery}` territories.

### Segmental Infarction

A `[well | ill]`-defined, **wedge-shaped** hypodense lesion involving ___, likely `{time}` segmental infarction of the `{artery}`. 

### Lacunar

`[A few | several]` (small) **well-defined hypodense lesions** at ___

likely chronic lacunar infarction(s) (or dilated perivascular space).

### Small VV dz

(Mild) patchy ill-defined hypodense `[changes | lesions]` involving (at)

-   `[lt | rt | bilat]` corona radiata

(These can DDx: CSF resorption)

-   {side} {lobe} white matter
-   periventricular white matter of {lobe}
-   deep white matter at bilateral cerebral hemispheres 

probably representing ischemic white matter change related to `[mild | moderate | severe]` degree of small vessel disease (or transependymal CSF resorption). 

**IMPRESSION:** 

-   (Mild) degree of small vessel disease.

### Chronic Infarction

A wedge-shaped hypodense lesion at ___, 

likely chronic infarction of the ___ artery territory. 

### Time Changes

-   **Subacute -> Chronic:** increased conspicuity and decreased attenuation

## Hemorrhage

### History

Known case of ___ with motorcycle accident and struck ??? to the ground.

### SDH

`[There is development of | Newly seen | New]`

-   (+) `[Acute | Subacute | Chronic]` subdural hematoma (SDH) along  

    -   `{side}` ___ convexity, 
    -   `{side}` tentorium cerebelli

**+ Thickness**

-   measuring up to ?? cm in **maximal thickness**. 

-   `{location-1}` (? cm-thick), `{location-2}` (? cm-thick)

**Other variant**

-   crescent-shaped `[isodense | hyperdense]` lesion along ___ convexity, about ?? cm in maximal thickness; likely representing `[Acute | Subacute | Chronic]` (on chronic) subdural hematoma (SDH).

**IMPRESSION:** 

-  `{time}` SDH along ___, measuring up to ? cm in maximal thickness.

- `[Increased | decreased]` thickness of __ subdural hematoma (SDH) along __.

-  Thin (? mm) `[Acute | Subacute | Chronic]` SDH along ___.


#### Acute-on-chronic SDH

-   Mixed hyper-hypodense subdural collections along ___, measuring up to 😳 cm, representing acute on chronic subdural hematoma (SDH).

**IMPRESSION:**

-   Acute ontop chronic SDH along ___. 


#### Thin SDH (doubtful)

-  Suspected thin hyperdense extra-axial lesion versus CT artifact at ___, measuring about ? mm in maximal thickness.


**IMPRESSION:** 

- Thin (? mm) hyperdense extra-axial lesion at ___, possibly CT artifact or thin acute subdural hematoma. Follow-up is recommended.

### EDH

- A small acute epidural hematoma at the ___. 

### SAH

SAH along 

-   (+) `[left | right | bilateral]` cerebral sulci
-   (+)  basal cistern
-   (+)  `[interpeduncular | perimesencephalic]` cisterns
-   (+) `[bilateral]` MCA cistern
-   (+) `[left | right | bilateral]` Sylvian fissure.

### Intraparenchymal

**Structure**

{time} intraparenchymal hemorrhage *epicenter* at the ____, involving ??? 

-   (+) with blood spillage into ___ ventricle

-   (+) with perilesional edema involving ____ {pressure effect ?}

**Chages** 

-   (interval) `[decreased | increased | no significant change]` (in) size and density of ___

**IMPRESSION:**

-   Acute intraparenchymal hematoma (? ml), **centered** at the ___, involving ____. 
    -   (+) with a few foci of active contrast extravasation

(This likely represents hypertensive hemorrhage.)


### Contusion

Hemorrhagic brain contusion at ___

### Subgaleal hematoma

**Calvarium and scalp:** Acute subgaleal hematoma (with associated scalp swelling) at ___ region, measuring about ? cm in maximal thickness. 

**IMPRESSION:**

-   Acute subgaleal hematoma with associated scalp swelling at ___ region.

### Active Bleed

**Spot sign**

-   CTA and post contrast series show few *enhancing foci* within this hematoma (spot sign), suggestive of active contrast extravasation. 

**IMPRESSION:**

Acute intraparenchymal hematoma ...... with (a few) foci of active contrast extravasation 

### Multi-compartment

Overall `[decreased | increased | no change of]` attenuation of multi-compartment intracranial hemorrhages, details as follows:

-   `[decreased | increased | no change of]` blah blah
-   ...

**Examples**

-   **(intraparenchymal):** `{time}` intraparenchymal hemorrhage (with perilesional edema) at ___ lobe, about ?x?x? cm in greatest transaxial and vertical dimensions, respectively.

-   **(air-blood-fluid):** extra-axial air-blood-fluid collections along ___, measuring up to ? cm in maximal thickness.

-   **(IVH):** (small) intraventricular hemorrhage (IVH) at ___.

-   **(SAH):** (acute) subarachnoid hemorrhage (SAH) along ___.

-   **(Air):** pneumocephalus along ___ convexity.




**IMPRESSION:**

Chronological change of multi-compartmental intracranial hemorrhage, including

-   Acute `{some-important-hemorrhage}` ...


## Pressure Effect

**Abbr:** midline shift or brain herniation

**Full**

-   `[left | right | bilateral]` uncal herniations
-   descending transtentorial herniations
-   crowding of the foramen magnum
-   tonsillar herniation

### No / Not change

No uncal herniation, descending transtentorial herniations, crowding of the foramen magnum, or tonsillar herniation is seen. 

No significant change of pressure effects, seen as ...

### Yes

(Associated) pressure effect `[causing | is seen as]` ...

-  (+) brain swelling

-  (+) ?-mm `rightward | leftward` **midline shift**

-  (+) (impending) ___ **herniation**

-  (+) effacement of the adjacent 

    -   `[left | right | bilateral]` `{lobe}` ___ **sulci**,
    -   ___ ventricle.

**IMPRESSION:** 

-   `Increased` pressure effects are seen as 

## Calcification

### Normal Calcification

**Ref:** [Normal intracranial calcification](https://radiopaedia.org/articles/12999)

A (small) (dense) calcification(s) `[at | along]`

-   `[bilateral]` globus pallidus.
-   falx cerebri
-   pineal gland 
-   parasagittal frontal lobe

(is noted.)


### Multiple Calcification

**Ref:** [Multiple calcification](https://radiopaedia.org/articles/8211) 

-   multiple scattered foci of calcifications in bilateral cerebral hemispheres, predominantly located along the gray-white matter junction.


**IMPRESSION:**

-   Multiple scattered foci of calcifications in bilateral cerebral hemispheres, likely representing sequelae of **chronic granulomatous disease** or **calcified neurocysticercosis**. Clinical correlation is required.  


## Chronic lesion

(Chronological change of ___, now seen as...)

encephalomalacia/gliosis change

-   (+) with volume loss, and

-   (+) associated ex-vacuo dilatation of the ___ ventricles.


**IMPRESSION:**

-   Sequelae of old traumatic contusion seen as encephalomalacia/gliosis change at ___ and associated ex-vacuo dilatation of ??? ventricles.

## Hydrocephalus

`{degree}` = `[mild | moderate | severe]`

-   `{degree}` obstructive hydrocephalus as evidenced by `{degree}` dilatation of the ___ ventricle. 

### Ex-vacuole

`{degree}` ex-vacuole dilatation of the ??? horn of ___ lateral ventricle.

### Evan's Index

**Ventricles:** `[No significant change]` of hydrocephalus with **Evans’ index** of ___ (the prior CT study revealed Evan's index of ???). No intraventricular hemorrhage. 

**IMPRESSION:**

- `[No significant change]` of (non-communicating) hydrocephalus with Evans’ index of ___.

## Degeneration

### Wallerian

Wallerian degeneration of the

-   {side} cerebral peduncle

is noted.

## Tumor

### Lipoma 

-   A tiny well-defined hypodense lesion at parasagittal region of right paracentral lobule, probably representing interhemispheric lipoma

## Post Op

-   Post-operative changes seen as ___

### Post-Op Tumor (Bad)

**History:** ... S/P craniotomy with tumor removal and decompression... He was sent to rule-out *post-operative bleeding*.

**Findings:** *Limited evaluation of residual tumor due to lack of IV contrast.* 

The study reveals evidence of `{side}` `{lobe}` craniotomy for tumor removal and decompression with details of postoperative changes as follows:

**(Collection)**

-   Newly seen an evidence of **air-blood-fluid collection** in surgical cavity and extra-axial space of the ___ convexities (?? cm) with connection to subgaleal air-fluid collection and scalp swelling at right frontoparietotemporal convexities, measuring about ? cm in maximal thickness. 

**(Edema + Pressure Effect)**

-   Associated surrounding vasogenic edema of the ___ lobe adjacent to the surgical site is observed. Note is made of an **increased pressure effect** seen as ......

**(Residual Tumor)**

- Suspected of residual tumor seen as an evidence of homogeneous hyperdense lesion involving ___

**(Hydrocephalus)**

- ___ degree of obstructive hydrocephalus seen as ..... dilatation of the ..... ventricle. 


**IMPRESSION:**

1. New evidence of ___ craniotomy for decompression with tumor removal with postoperative changes as described above. 

2. Increased pressure effect with ___.

3. Suspected the residual tumor seen as an evidence of ___

4. No acute intracranial hemorrhage or acute large territorial infarction


### Craniotomy 

Evidence of ___ **craniotomy** is noted, (with VP shunt)

along with post-operative changes seen as 

-   (+) dural thickening with calcification along ___ 

-   (+) (small) extradural fluid collection, measuring up to __ mm in maximal thickness. 

-   (+) `[Increased | Decreased]` degree of scalp swelling and soft tissue gas along surgical site. 

**IMPRESSION:** 

- Post ___ craniotomy, with post operative changes seen as dural thickening and calcification. `(small)` extradural fluid collection is still noted.

### Dural Thickening / Calcify

No significant change of calcified dural thickening at the `[lt | rt]` cerebral convexity craniotomy site.

### Burr hole

#### SDH s/p burr holes 

-   **air-fluid-blood:** The study reveals new evidence of `{location}` burr holes for subdural clot irrigation, now leaving **air-fluid-blood collection** along the ___, measuring up to ?. 
 
-   **Pressure:** Decreased pressure effect seen ___. 
 
-   **Scalp:** Subgaleal collection and scalp edema along the both-sided head are observed, likely postoperative change.  


## Tube / Line

### Enteric

-   Enteric tube via ___ nostril (without visualized its tips) is noted. 


### VP Shunt

**Cerebral parenchyma and extra-axial spaces:** ___ craniotomy with ventricular shunt via ??? approach, which the tip is at the ??? of ??? lateral ventricle abutting the ???.


**IMPRESSION:**

-   No change in position of `[lt | rt]` ventricular shunt with its tip in the ___ of ??? lateral ventricle.