project:
  type: website
  output-dir: _site

website:
  title: "LB Radiology"
  author: "Kittipos Sirivongrungson"
  description: |
    My Personal Website for Radiology Knowledge Collection
  date: now

  site-url: https://radio-lightbridge.netlify.app
  repo-url: https://github.com/Lightbridge-KS/radio-web
  repo-actions: [edit]
  page-navigation: true

  page-footer: 
    center: 
      - icon: github
        href: https://github.com/Lightbridge-KS/radio-web
        aria-label: LB Radiology GitHub
    right: 
      - text: "License"
        href: LICENSE.md
  navbar:
    background: light
    collapse-below: lg
    right:
      - icon: github
        href: https://github.com/Lightbridge-KS/radio-web
        aria-label: GitHub
    left:
      - href: index.qmd
        text: Home
      - href: "docs/resources.qmd"
        text: Resources
      - href: "docs/rotations/index.qmd"
        text: Rotations
      - href: "docs/templates/index.qmd"
        text: Templates
      - about.qmd

  sidebar: 
    # Templates
    - id: templates
      collapse-level: 1
      align: left
      style: "docked"  # "floating"
      contents: 
      - href: "docs/templates/index.qmd"
        text: About
      - "docs/templates/style.qmd"
      - section: Neurology
        contents:
        - "docs/templates/neuro/tmp-stroke-fast.qmd"
        - "docs/templates/neuro/tmp-ct-brain-loc.qmd"
        - "docs/templates/neuro/tmp-ct-brain-lesion.qmd"
      - section: Ultrasound
        contents:
        - "docs/templates/us/tmp-us-abdo.qmd"
        - "docs/templates/us/tmp-us-thyroid.qmd"
        - "docs/templates/us/tmp-us-scrotum.qmd"
      - section: CVS
        contents:
        - "docs/templates/cvs/tmp-doppler.qmd"
      - section: Chest
        contents:
        - "docs/templates/chest/tmp-cxr.qmd"
    
    # Rotations by Systems
    - id: rotations
      collapse-level: 1
      align: left
      style: "floating"
      contents: 
      - href: "docs/rotations/index.qmd"
        text: About
      - section: ER
        contents:
        - "docs/rotations/er/contrast.qmd"
        - "docs/rotations/er/stroke-fast.qmd"
      - section: Ultrasound
        contents:
        - "docs/rotations/us/us-q-ref.qmd"
        - "docs/rotations/us/us-scan-abdo.qmd"

# Not show source code
execute: 
  echo: false

format:
  html:
    theme: 
      light: cosmo 
      dark: slate
    css: styles.css
    toc: true

# Bibliography
bibliography: "assets/references.bib"
csl: "assets/elsevier-with-titles.csl"

freeze: auto