---
title: "CXR CVS Template"
---

## Normal

**CHEST (PA UPRIGHT) (AP SUPINE) **

**HISTORY:** Known case ____, was sent to follow-up. 

**COMPARISON:** Chest radiograph on _____. 

**FINDINGS:** 

-   **Tubes and lines:** None. 
-   **Lungs and trachea:** Normal lung volumes. No abnormal pulmonary opacity. 
-   **Diaphragm, pleura and costophrenic angles:** No pneumothorax or pleural effusion. 
-   **Heart and mediastinum:** Normal cardiac silhouette. Normal mediastinal contour. Tortuous aorta ?. 
-   **Bony structures:** Unremarkable for age. Degenerative change of the spine.
-   **Upper abdomen:** Unremarkable. 

**IMPRESSION:**

-   No abnormal pulmonary opacity.

## Tube & lines

-   Tip of enteric tube in stomach

## Lung

### Adequacy

-   Suboptimal inspiration

### Summation

-   Symmetrical subtle patchy ground glass opacities at periphery of bilateral lower lung zones; probably summation of breast tissues.

### Aging

-   Diffuse mild tortuous lung marking at both lungs could be due to aging process.

### Atelectasis

#### Subsegmental Atelect

-   Subsegmental atelectasis/fibrosis at ___ zone.

#### Plate Atelect

-   Linear opacity at left ___ lung zone, probably plate atelectasis/fibrosis.

## Heart & Mediastinum

### Cardiomegaly

-   {degree} cardiomegaly (with atherosclerotic change of the aorta)

-   Enlarged cardiac silhouette; probably relate to suboptimal inspiration or true opacity.

### Pulmonary Venous HTN

**Lungs and trachea:** 

-   `[Cephalization | increased redistribution]` of the pulmonary vessels

-   (+) Diffuse interstitial opacities

-   (+) Peribronchial cuffing

-   (+) Blurring of pulmonary vasculature | perihilar haziness


in both lungs (with Kerley B lines), likely representing 

-   Interstitial pulmonary edema.



**(Follow-Up)** Increased degree of interstitial pulmonary edema, seen as ...


**Diaphragm, pleura and costophrenic angles:** (Minimal) Fluid in right minor fissure.

**Heart and mediastinum:** Increased pulmonary vasculature.

**IMPRESSION:**

-   Cardiomegaly with pulmonary edema.

### Pulmonary Arterial HTN

**Heart and mediastinum:** Enlargement of the MPA and right descending interlobar pulmonary artery with rapid tapering of distal pulmonary artery.

**IMPRESSION:**

-   Enlargement of the MPA and right descending lobar pulmonary artery, concerning for pulmonary arterial hypertension. `{echo + clinical corr}`



### Aorta

-   Tortuous aorta.
-   [Marked] tortuosity of the (descending) thoracic aorta, unchanged.
-   Calcified aortic knob.

### Surgery

-   Evidence of median sternotomy with intact median sternal wires.

-   Evidence of CABG

### Stent

-   Evidence of coronary stents, unchanged.

### Prosthetic Valve

-   Seen prosthetic aortic valve

## Bony 

-   Degenerative change of spine.

## Diaphragm

### Eventration

-   (Persistent) of focal lobulated contour of the ___ hemidiaphragm, probably focal eventration or focal diaphragmatic defect related to remote diaphragmatic injury.

## Pleura

### Effusion

**Mild**

-   Mild Blunting of the ___ costophrenic angle(s), probably small amount of pleural effusion or pleural thicking.

**Moderate**

-   Decreased `{side}` lung volume with `[increased | decreased]` amount of `{side}` pleural effusion and passive atelectasis of `[RLL | LLL]`.


### Pleural thickening

-   Persistent blunting of the ___ costophrenic angle(s), probably pleural thicking.


## Abdomen

### Gallstone

-   Round calcification at RUQ abdomen, likely calcified gallstone.

## Recommend


-   **Echo + Clinical:** Correlation with echocardiogram and clinical contex are reccommended.