---
title: "Resources"
---


## Calculator

-   [RadCalc](https://radcalculators.org): Scoring and reporting system calculators

## Anatomy

-   [Labelled Imaging Anatomy](https://radiopaedia.org/articles/62414): Plain film / CT / MRI by body region and modality.

-   [Normal CTA Head & Neck](https://bit.ly/CTAnormal): claripacs

## Reading

-   [Top 10 Reading List](https://pubs.rsna.org/page/radiographics/rgteam/top10Home): by radiographics

## Society

### US

- [ACR](https://www.acr.org): American College of Radiology
- [RSNA](https://www.rsna.org): Radiology Society of North America (free regis)
- [ASNR](https://www.asnr.org): American Society of Neuroradiology (free regis)
- [MSK Core lecture](https://radiologycorelectures.org/msk/): good MSK lecture

### Thai

- [RCRT](https://www.rcrt.or.th)
- [RCRT Education Enhancement](http://eden.rcrt.or.th)


## RAMA

- [STATdx](https://www.rama.mahidol.ac.th/library/th/E_databases/databasess/05262017-1511-th): via RAMA Wifi only
- [Moodle RadRAMA](https://radiology.mahidol.ac.th/moodle/)
- [Resident curriculum](https://www.rama.mahidol.ac.th/radiology/th/content/academix-th)

## SI

- [SIRAD Hub](https://sites.google.com/view/sirad-education/home?authuser=0)
- [Radio material for Med Student SI](https://drive.google.com/drive/folders/0BzwV_ek8RCZWfmtjT3kydE9LZGJlODZQQmpydG9MRGdlWlFWY3NCRU1aRlEyUUktY1RhZFU?resourcekey=0-EIKtGE5o7PaPsIo4z7s-7A&usp=sharing)


## MU

- [MUIT](https://muit.mahidol.ac.th)
- [E-journal](https://login.ejournal.mahidol.ac.th/login)
- [IT-Portal](https://it-portal.mahidol.ac.th): MU WebEx, Office 365, MU Digital ID

## Library

- [Library RAMA](https://www.rama.mahidol.ac.th/library/)
- [Library MU](https://www.li.mahidol.ac.th)

## Research

- [RAMA Research ethics](https://www.rama.mahidol.ac.th/research/ethics/): you need this when conducting research project in human subject